### ISSUE TITLE
Bug in confdistmatrix.py

### ISSUE THREAD

**Issue by SGenheden** [wouterboomsma/encore#1]
Line 153 reads:

```
workers = [Process(target=self._simple_worker, args=(tasks_per_worker[i], ensemble.coordinates, masses, distmat, pbar_counter))
```

but `pbar_counter` is undefined leading to the error

```
NameError: global name 'pbar_counter' is not defined
```

Should it be `partial_counters[i]`instead as when `pairwise_align` is true?

**Comment by mtiberti** [comment]
Hi,
Thanks for the bug report, and for your interest in encore! Yes indeed, you are right - I just pushed the fix you have suggested on the repository.
